spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: "health, info"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true