name: Build test

on:
  push:
    branches: ['**']

jobs:
  build:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: run build
        run: ./gradlew clean build
